-- 072 — Phase 8H polish: spx_city_coverage RPC (input-time coverage check).
-- Applied via Supabase MCP (apply_migration: phase8h_coverage_area_spx).
--
-- Pelengkap migration 061-062 (157 non-coverage cities + export-time check).
-- RPC ini dipakai di INPUT-side: form /orders/new manggil setelah user pilih
-- city → kasih warning lebih awal sebelum order tersimpan.
--
-- Input: province + city dalam format lokal (master_wilayah). RPC auto-strip
-- prefix "Kab."/"Kota " supaya match ke state_normalized + city_normalized
-- di master_wilayah_spx (yang sudah lowercased + tanpa prefix per Phase 8G).
--
-- Output text status:
--   - 'NOT_COVERED' — semua district di city ini is_serviceable=FALSE
--   - 'COVERED'     — semua serviceable
--   - 'PARTIAL'     — campur (mis. Pekalongan: KAB tidak cover, KOTA cover)
--   - 'UNKNOWN'     — city tidak ditemukan di master_wilayah_spx
--
-- Plus safety-net idempotent UPDATE — handle outliers (mis. 1 dari 20 baris
-- PAPUA/KAB. ASMAT yang sebelumnya tertinggal is_serviceable=TRUE).

UPDATE public.master_wilayah_spx s
SET is_serviceable = FALSE
FROM (VALUES
  ('BALI','KAB. BADUNG'),
  ('BENGKULU','KAB. BENGKULU UTARA'),
  ('GORONTALO','KAB. BONE BOLANGO'),
  ('GORONTALO','KAB. GORONTALO'),
  ('GORONTALO','KAB. GORONTALO UTARA'),
  ('JAMBI','KAB. MERANGIN'),
  ('JAWA TENGAH','KAB. PEKALONGAN'),
  ('KALIMANTAN BARAT','KAB. BENGKAYANG'),
  ('KALIMANTAN BARAT','KAB. KAYONG UTARA'),
  ('KALIMANTAN BARAT','KAB. KETAPANG'),
  ('KALIMANTAN BARAT','KAB. LANDAK'),
  ('KALIMANTAN SELATAN','KAB. BANJAR'),
  ('KALIMANTAN SELATAN','KAB. BARITO KUALA'),
  ('KALIMANTAN SELATAN','KAB. HULU SUNGAI UTARA'),
  ('KALIMANTAN SELATAN','KAB. KOTA BARU'),
  ('KALIMANTAN TENGAH','KAB. BARITO SELATAN'),
  ('KALIMANTAN TENGAH','KAB. BARITO UTARA'),
  ('KALIMANTAN TENGAH','KAB. GUNUNG MAS'),
  ('KALIMANTAN TENGAH','KAB. KAPUAS'),
  ('KALIMANTAN TENGAH','KAB. KATINGAN'),
  ('KALIMANTAN TENGAH','KAB. KOTA WARINGIN BARAT'),
  ('KALIMANTAN TENGAH','KAB. KOTA WARINGIN TIMUR'),
  ('KALIMANTAN TENGAH','KAB. LAMANDAU'),
  ('KALIMANTAN TENGAH','KAB. MURUNG RAYA'),
  ('KALIMANTAN TENGAH','KAB. SERUYAN'),
  ('KALIMANTAN TIMUR','KAB. BERAU'),
  ('KALIMANTAN TIMUR','KAB. KUTAI BARAT'),
  ('KALIMANTAN TIMUR','KAB. KUTAI KARTANEGARA'),
  ('KALIMANTAN TIMUR','KAB. KUTAI TIMUR'),
  ('KALIMANTAN TIMUR','KAB. MAHAKAM ULU'),
  ('KALIMANTAN UTARA','KAB. BULUNGAN (BULONGAN)'),
  ('KALIMANTAN UTARA','KAB. MALINAU'),
  ('KALIMANTAN UTARA','KAB. NUNUKAN'),
  ('KALIMANTAN UTARA','KAB. TANA TIDUNG'),
  ('KEPULAUAN RIAU','KAB. BINTAN'),
  ('KEPULAUAN RIAU','KAB. LINGGA'),
  ('KEPULAUAN RIAU','KAB. NATUNA'),
  ('MALUKU UTARA','KAB. HALMAHERA BARAT'),
  ('MALUKU UTARA','KAB. HALMAHERA SELATAN'),
  ('MALUKU UTARA','KAB. HALMAHERA TENGAH'),
  ('MALUKU UTARA','KAB. HALMAHERA TIMUR'),
  ('MALUKU UTARA','KAB. HALMAHERA UTARA'),
  ('MALUKU UTARA','KAB. KEPULAUAN SULA'),
  ('MALUKU UTARA','KAB. PULAU MOROTAI'),
  ('MALUKU UTARA','KAB. PULAU TALIABU'),
  ('MALUKU UTARA','KOTA TERNATE'),
  ('MALUKU UTARA','KOTA TIDORE KEPULAUAN'),
  ('MALUKU','KAB. BURU'),
  ('MALUKU','KAB. BURU SELATAN'),
  ('MALUKU','KAB. KEPULAUAN ARU'),
  ('MALUKU','KAB. MALUKU BARAT DAYA'),
  ('MALUKU','KAB. MALUKU TENGAH'),
  ('MALUKU','KAB. MALUKU TENGGARA'),
  ('MALUKU','KAB. MALUKU TENGGARA BARAT'),
  ('MALUKU','KAB. SERAM BAGIAN BARAT'),
  ('MALUKU','KAB. SERAM BAGIAN TIMUR'),
  ('MALUKU','KOTA TUAL'),
  ('NANGGROE ACEH DARUSSALAM (NAD)','KAB. ACEH SELATAN'),
  ('NANGGROE ACEH DARUSSALAM (NAD)','KAB. ACEH SINGKIL'),
  ('NANGGROE ACEH DARUSSALAM (NAD)','KAB. NAGAN RAYA'),
  ('NUSA TENGGARA BARAT (NTB)','KAB. SUMBAWA'),
  ('NUSA TENGGARA TIMUR (NTT)','KAB. ALOR'),
  ('NUSA TENGGARA TIMUR (NTT)','KAB. BELU'),
  ('NUSA TENGGARA TIMUR (NTT)','KAB. ENDE'),
  ('NUSA TENGGARA TIMUR (NTT)','KAB. FLORES TIMUR'),
  ('NUSA TENGGARA TIMUR (NTT)','KAB. KUPANG'),
  ('NUSA TENGGARA TIMUR (NTT)','KAB. MALAKA'),
  ('NUSA TENGGARA TIMUR (NTT)','KAB. MANGGARAI'),
  ('NUSA TENGGARA TIMUR (NTT)','KAB. MANGGARAI BARAT'),
  ('NUSA TENGGARA TIMUR (NTT)','KAB. MANGGARAI TIMUR'),
  ('NUSA TENGGARA TIMUR (NTT)','KAB. NAGEKEO'),
  ('NUSA TENGGARA TIMUR (NTT)','KAB. NGADA'),
  ('NUSA TENGGARA TIMUR (NTT)','KAB. ROTE NDAO'),
  ('NUSA TENGGARA TIMUR (NTT)','KAB. SIKKA'),
  ('NUSA TENGGARA TIMUR (NTT)','KAB. SUMBA BARAT'),
  ('NUSA TENGGARA TIMUR (NTT)','KAB. SUMBA TENGAH'),
  ('NUSA TENGGARA TIMUR (NTT)','KAB. SUMBA TIMUR'),
  ('NUSA TENGGARA TIMUR (NTT)','KAB. TIMOR TENGAH SELATAN'),
  ('NUSA TENGGARA TIMUR (NTT)','KAB. TIMOR TENGAH UTARA'),
  ('PAPUA BARAT','KAB. MANOKWARI'),
  ('PAPUA BARAT','KAB. MANOKWARI SELATAN'),
  ('PAPUA BARAT','KAB. MAYBRAT'),
  ('PAPUA BARAT','KAB. RAJA AMPAT'),
  ('PAPUA BARAT','KAB. SORONG SELATAN'),
  ('PAPUA BARAT','KAB. TAMBRAUW'),
  ('PAPUA BARAT','KAB. TELUK BINTUNI'),
  ('PAPUA BARAT','KAB. TELUK WONDAMA'),
  ('PAPUA BARAT','KOTA SORONG'),
  ('PAPUA','KAB. ASMAT'),
  ('PAPUA','KAB. BIAK NUMFOR'),
  ('PAPUA','KAB. BOVEN DIGOEL'),
  ('PAPUA','KAB. DEIYAI (DELIYAI)'),
  ('PAPUA','KAB. DOGIYAI'),
  ('PAPUA','KAB. INTAN JAYA'),
  ('PAPUA','KAB. JAYAPURA'),
  ('PAPUA','KAB. JAYAWIJAYA'),
  ('PAPUA','KAB. MAMBERAMO TENGAH'),
  ('PAPUA','KAB. MAPPI'),
  ('PAPUA','KAB. MERAUKE'),
  ('PAPUA','KAB. MIMIKA'),
  ('PAPUA','KAB. NABIRE'),
  ('PAPUA','KAB. NDUGA'),
  ('PAPUA','KAB. PANIAI'),
  ('PAPUA','KAB. PEGUNUNGAN BINTANG'),
  ('PAPUA','KAB. PUNCAK JAYA'),
  ('PAPUA','KAB. SARMI'),
  ('PAPUA','KAB. WAROPEN'),
  ('PAPUA','KAB. YAHUKIMO'),
  ('PAPUA','KAB. YALIMO'),
  ('RIAU','KAB. BENGKALIS'),
  ('RIAU','KAB. INDRAGIRI HILIR'),
  ('RIAU','KAB. KEPULAUAN MERANTI'),
  ('SULAWESI BARAT','KAB. MAMASA'),
  ('SULAWESI BARAT','KAB. MAMUJU'),
  ('SULAWESI BARAT','KAB. POLEWALI MANDAR'),
  ('SULAWESI SELATAN','KAB. LUWU'),
  ('SULAWESI SELATAN','KAB. LUWU TIMUR'),
  ('SULAWESI SELATAN','KAB. LUWU UTARA'),
  ('SULAWESI SELATAN','KAB. PANGKAJENE KEPULAUAN'),
  ('SULAWESI SELATAN','KAB. SELAYAR (KEPULAUAN SELAYAR)'),
  ('SULAWESI SELATAN','KAB. SINJAI'),
  ('SULAWESI SELATAN','KAB. TANA TORAJA'),
  ('SULAWESI SELATAN','KAB. TORAJA UTARA'),
  ('SULAWESI TENGAH','KAB. BANGGAI'),
  ('SULAWESI TENGAH','KAB. BANGGAI LAUT'),
  ('SULAWESI TENGAH','KAB. DONGGALA'),
  ('SULAWESI TENGAH','KAB. MOROWALI'),
  ('SULAWESI TENGAH','KAB. MOROWALI UTARA'),
  ('SULAWESI TENGAH','KAB. PARIGI MOUTONG'),
  ('SULAWESI TENGAH','KAB. POSO'),
  ('SULAWESI TENGAH','KAB. SIGI'),
  ('SULAWESI TENGAH','KAB. TOJO UNA-UNA'),
  ('SULAWESI TENGGARA','KAB. BOMBANA'),
  ('SULAWESI TENGGARA','KAB. BUTON SELATAN'),
  ('SULAWESI TENGGARA','KAB. BUTON TENGAH'),
  ('SULAWESI TENGGARA','KAB. BUTON UTARA'),
  ('SULAWESI TENGGARA','KAB. KOLAKA TIMUR'),
  ('SULAWESI TENGGARA','KAB. KONAWE'),
  ('SULAWESI TENGGARA','KAB. KONAWE KEPULAUAN'),
  ('SULAWESI TENGGARA','KAB. KONAWE SELATAN'),
  ('SULAWESI TENGGARA','KAB. KONAWE UTARA'),
  ('SULAWESI TENGGARA','KAB. MUNA'),
  ('SULAWESI TENGGARA','KAB. MUNA BARAT'),
  ('SULAWESI TENGGARA','KOTA BAU-BAU'),
  ('SULAWESI UTARA','KAB. KEPULAUAN SANGIHE'),
  ('SULAWESI UTARA','KAB. KEPULAUAN SIAU TAGULANDANG BIARO (SITARO)'),
  ('SULAWESI UTARA','KAB. KEPULAUAN TALAUD'),
  ('SULAWESI UTARA','KAB. MINAHASA SELATAN'),
  ('SULAWESI UTARA','KAB. MINAHASA UTARA'),
  ('SULAWESI UTARA','KOTA BITUNG'),
  ('SULAWESI UTARA','KOTA MANADO'),
  ('SUMATERA BARAT','KAB. KEPULAUAN MENTAWAI'),
  ('SUMATERA SELATAN','KAB. LAHAT'),
  ('SUMATERA UTARA','KAB. NIAS'),
  ('SUMATERA UTARA','KAB. NIAS SELATAN'),
  ('SUMATERA UTARA','KAB. PADANG LAWAS UTARA'),
  ('SUMATERA UTARA','KAB. PAKPAK BHARAT')
) AS nc(state, city)
WHERE s.state = nc.state AND s.city = nc.city AND s.is_serviceable = TRUE;

CREATE OR REPLACE FUNCTION public.spx_city_coverage(p_province text, p_city text)
RETURNS text
LANGUAGE plpgsql
STABLE SECURITY INVOKER
SET search_path TO 'public'
AS $func$
DECLARE
  v_p text;
  v_c text;
  v_total int;
  v_svc int;
BEGIN
  v_p := lower(btrim(coalesce(p_province, '')));
  v_c := lower(regexp_replace(btrim(coalesce(p_city, '')), '^(kab\.?|kota|kabupaten|kotamadya)\s+', '', 'i'));
  IF v_p = '' OR v_c = '' THEN RETURN 'UNKNOWN'; END IF;

  SELECT COUNT(*), COUNT(*) FILTER (WHERE is_serviceable)
  INTO v_total, v_svc
  FROM public.master_wilayah_spx
  WHERE state_normalized = v_p AND city_normalized = v_c;

  IF v_total = 0 THEN RETURN 'UNKNOWN'; END IF;
  IF v_svc = 0 THEN RETURN 'NOT_COVERED'; END IF;
  IF v_svc = v_total THEN RETURN 'COVERED'; END IF;
  RETURN 'PARTIAL';
END;
$func$;

GRANT EXECUTE ON FUNCTION public.spx_city_coverage(text, text) TO authenticated;
